[package]
name = "compile_with_bazel"
version = "0.0.0"

[lib]
path = "fake_lib.rs"

[dependencies]
regex = "1.3.9"

[raze]
workspace_path = "//cargo"
output_buildfile_suffix = "BUILD.bazel"
default_gen_buildrs = true
genmode = "Remote"
target = "x86_64-unknown-linux-gnu"
gen_buildrs = true
