#!/bin/bash
set -eu

readonly _dir="$(dirname "$0")"

readonly WORKSPACE_ROOT=$(git rev-parse --show-toplevel)
cd "${WORKSPACE_ROOT}/cargo"

rm -rf remote/*.BUILD.bazel
../tools/bin/cargo-raze
"$_dir/buildifier"
cargo generate-lockfile
