#!/bin/bash
set -eu

readonly WORKSPACE_ROOT=$(git rev-parse --show-toplevel)
cd "${WORKSPACE_ROOT}/cargo"

rm -rf remote/*.BUILD.bazel
../tools/bin/cargo-raze

if [[ "${1:-}" == update ]]; then
    cargo generate-lockfile
fi
