#!/bin/bash
set -euo pipefail

platform=linux
if [ "$(uname -s)" == "Darwin" ]; then
    platform=darwin
fi

[[ -n "$*" ]] && exec bazel run "@rust_${platform}_x86_64//:rustfmt" -- "$@"

git ls-files |
    grep -E ".rs$" |
    sed -e "s|^|$PWD/|" |
    xargs "$0" --edition 2018
