name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        name: Bootstrap
        run: ./tools/scripts/bootstrap.sh

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        name: Bootstrap
        run: ./tools/ci/ci-test.sh
