name: CI

on:
  push:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: bazel-${{ hashFiles('.bazelversion') }}

      - name: Mount cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            cargo/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('cargo/**/Cargo.lock') }}

      - name: Mount tools
        uses: actions/cache@v2
        with:
          path: |
            tools/bin/
            tools/.crates.toml
            tools/.crates2.json
          key: ${{ runner.os }}-tools-${{ hashFiles('tools/scripts/bootstrap.sh') }}

      - name: Bootstrap
        run: ./tools/scripts/bootstrap.sh

      - name: Build/Test
        run: ./tools/ci/ci-test.sh

      - name: Collect artifacts
        # TODO: remove when github actions support symlinks
        run: ./tools/ci/ci-collect.sh

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./artifacts/test-results/
          if-no-files-found: error

      - name: Upload godot
        uses: actions/upload-artifact@v2
        with:
          name: godot
          path: ./artifacts/debs/src/cmd/godot/godot-debian.deb
          if-no-files-found: error
